name: Build

on: workflow_call

concurrency:
  group: build-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Self-service front
    runs-on: ubuntu-latest
    defaults:
      run: { working-directory: express }

    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          cache-dependency-path: express/package-lock.json

      - name: Install Node dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Archive distribution artifact
        uses: actions/upload-artifact@v2
        with:
          name: self-service-front
          retention-days: 7
          path: |
            express/dist
            express/src/views
            express/package*.json
            express/manifest.yml
            express/valid-email-domains.txt
            express/stubs-config.json
