name: Deploy branch

on: workflow_dispatch

jobs:
  build-front:
    name: Build
    uses: ./.github/workflows/build-front.yml

  deploy-front-preview:
    name: Preview
    needs: build
    uses: ./.github/workflows/deploy-to-paas.yml
    with:
      environment: preview
      cf-space-name: self-service-preview
      app-name-prefix: di-sse-prev
      cognito-client: StubCognitoClient
      lambda-facade: StubLambdaFacade
    secrets:
      cf-username: ${{ secrets.CF_USERNAME }}
      cf-password: ${{ secrets.CF_PASSWORD }}
